-- MySQL Script generated by MySQL Workbench
-- Wed Mar 29 12:44:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Traveling Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Traveling Company` (
  `company_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Driver Specialty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Driver Specialty` (
  `Driver Specialty id` INT NOT NULL,
  `licence category` VARCHAR(45) NOT NULL,
  `experiencetime` VARCHAR(45) NOT NULL,
  `Capability to drive in foreign coutry` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Driver Specialty id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Languages` (
  `languages id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`languages id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tour Guide`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tour Guide` (
  `Tour Guide id` INT NOT NULL,
  `Bio` VARCHAR(45) NOT NULL,
  `Languages id` INT NOT NULL,
  PRIMARY KEY (`Tour Guide id`, `Languages id`),
  INDEX `fk_Tour Guide_Languages1_idx` (`Languages id` ASC) VISIBLE,
  CONSTRAINT `fk_Tour Guide_Languages1`
    FOREIGN KEY (`Languages id`)
    REFERENCES `mydb`.`Languages` (`languages id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IT` (
  `IT id` INT NOT NULL,
  `Bio` VARCHAR(45) NOT NULL,
  `MasterCode` VARCHAR(45) NULL,
  PRIMARY KEY (`IT id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrative` (
  `Administrative id` INT NOT NULL,
  PRIMARY KEY (`Administrative id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Accounting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Accounting` (
  `Accounting id` INT NOT NULL,
  PRIMARY KEY (`Accounting id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Logistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Logistics` (
  `Logistics id` INT NOT NULL,
  PRIMARY KEY (`Logistics id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chief Specialities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chief Specialities` (
  `Chief Speciality id` INT NOT NULL,
  `Administrative_Administrative id` INT NULL,
  `Accounting_Accounting id` INT NULL,
  `IT_IT id` INT NULL,
  `Logistics_Logistics id` INT NULL,
  PRIMARY KEY (`Chief Speciality id`),
  INDEX `fk_Chief Specialities_Administrative1_idx` (`Administrative_Administrative id` ASC) VISIBLE,
  INDEX `fk_Chief Specialities_Accounting1_idx` (`Accounting_Accounting id` ASC) VISIBLE,
  INDEX `fk_Chief Specialities_IT1_idx` (`IT_IT id` ASC) VISIBLE,
  INDEX `fk_Chief Specialities_Logistics1_idx` (`Logistics_Logistics id` ASC) VISIBLE,
  CONSTRAINT `fk_Chief Specialities_Administrative1`
    FOREIGN KEY (`Administrative_Administrative id`)
    REFERENCES `mydb`.`Administrative` (`Administrative id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chief Specialities_Accounting1`
    FOREIGN KEY (`Accounting_Accounting id`)
    REFERENCES `mydb`.`Accounting` (`Accounting id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chief Specialities_IT1`
    FOREIGN KEY (`IT_IT id`)
    REFERENCES `mydb`.`IT` (`IT id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chief Specialities_Logistics1`
    FOREIGN KEY (`Logistics_Logistics id`)
    REFERENCES `mydb`.`Logistics` (`Logistics id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chief Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chief Employee` (
  `Chief Employee id` INT NOT NULL,
  `degree` VARCHAR(45) NOT NULL,
  `Chief Specialities id` INT NOT NULL,
  PRIMARY KEY (`Chief Employee id`),
  INDEX `fk_chief Employee_Chief Specialities1_idx` (`Chief Specialities id` ASC) VISIBLE,
  CONSTRAINT `fk_chief Employee_Chief Specialities1`
    FOREIGN KEY (`Chief Specialities id`)
    REFERENCES `mydb`.`Chief Specialities` (`Chief Speciality id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sub Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sub Store` (
  `SubStore_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `Traveling Company_id` INT NOT NULL,
  `Driver Specialty id` INT NOT NULL,
  `Tour Guide id` INT NOT NULL,
  `Head IT id` INT NOT NULL,
  `Chief Employee id` INT NOT NULL,
  `Traveling Company id` INT NOT NULL,
  PRIMARY KEY (`SubStore_id`),
  INDEX `fk_Sub Store_Driver Specialty1_idx` (`Driver Specialty id` ASC) VISIBLE,
  INDEX `fk_Sub Store_Tour Guide1_idx` (`Tour Guide id` ASC) VISIBLE,
  INDEX `fk_Sub Store_IT1_idx` (`Head IT id` ASC) VISIBLE,
  INDEX `fk_Sub Store_chief Employee1_idx` (`Chief Employee id` ASC) VISIBLE,
  INDEX `fk_Sub Store_Traveling Company1_idx` (`Traveling Company id` ASC) VISIBLE,
  CONSTRAINT `fk_Sub Store_Driver Specialty1`
    FOREIGN KEY (`Driver Specialty id`)
    REFERENCES `mydb`.`Driver Specialty` (`Driver Specialty id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sub Store_Tour Guide1`
    FOREIGN KEY (`Tour Guide id`)
    REFERENCES `mydb`.`Tour Guide` (`Tour Guide id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sub Store_IT1`
    FOREIGN KEY (`Head IT id`)
    REFERENCES `mydb`.`IT` (`IT id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sub Store_chief Employee1`
    FOREIGN KEY (`Chief Employee id`)
    REFERENCES `mydb`.`chief Employee` (`Chief Employee id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sub Store_Traveling Company1`
    FOREIGN KEY (`Traveling Company id`)
    REFERENCES `mydb`.`Traveling Company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Specialty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Specialty` (
  `Specialty id` INT NOT NULL,
  `Driver id` INT NULL,
  `Tour Guide id` INT NULL,
  `Chief Employee id` INT NULL,
  PRIMARY KEY (`Specialty id`),
  INDEX `fk_Specialty_Driver Specialty1_idx` (`Driver id` ASC) VISIBLE,
  INDEX `fk_Specialty_Tour Guide1_idx` (`Tour Guide id` ASC) VISIBLE,
  INDEX `fk_Specialty_chief Employee1_idx` (`Chief Employee id` ASC) VISIBLE,
  CONSTRAINT `fk_Specialty_Driver Specialty1`
    FOREIGN KEY (`Driver id`)
    REFERENCES `mydb`.`Driver Specialty` (`Driver Specialty id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specialty_Tour Guide1`
    FOREIGN KEY (`Tour Guide id`)
    REFERENCES `mydb`.`Tour Guide` (`Tour Guide id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specialty_chief Employee1`
    FOREIGN KEY (`Chief Employee id`)
    REFERENCES `mydb`.`chief Employee` (`Chief Employee id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `employee_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `MotherNumber` VARCHAR(45) NOT NULL,
  `subname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `tax_number` VARCHAR(45) NOT NULL,
  `salery` VARCHAR(45) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL,
  `Sub Store id` INT NOT NULL,
  `Specialty id` INT NOT NULL,
  `Sub Store_Traveling Company_id` INT NULL,
  `Sub Store_Driver Specialty id` INT NULL,
  `Sub Store_Tour Guide id` INT NULL,
  `Sub Store_Head IT id` INT NULL,
  `Sub Store_Chief Employee id` INT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `fk_Employee_Sub Store1_idx` (`Sub Store id` ASC) VISIBLE,
  INDEX `fk_Employee_Specialty1_idx` (`Specialty id` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Sub Store1`
    FOREIGN KEY (`Sub Store id`)
    REFERENCES `mydb`.`Sub Store` (`SubStore_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_Specialty1`
    FOREIGN KEY (`Specialty id`)
    REFERENCES `mydb`.`Specialty` (`Specialty id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`phone` (
  `phone_id` INT NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `Sub Store id` INT NOT NULL,
  PRIMARY KEY (`phone_id`, `Sub Store id`),
  INDEX `fk_phone_Sub Store1_idx` (`Sub Store id` ASC) VISIBLE,
  CONSTRAINT `fk_phone_Sub Store1`
    FOREIGN KEY (`Sub Store id`)
    REFERENCES `mydb`.`Sub Store` (`SubStore_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Restaurant Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Restaurant Event` (
  `Restaurant Event` INT NOT NULL,
  PRIMARY KEY (`Restaurant Event`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Club Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Club Event` (
  `Club Event id` INT NOT NULL,
  PRIMARY KEY (`Club Event id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Events` (
  `Event Id` INT NOT NULL,
  `Restaurant Event_Restaurant Event` INT NULL,
  `Club Event_Club Event id` INT NULL,
  PRIMARY KEY (`Event Id`),
  INDEX `fk_Events_Restaurant Event1_idx` (`Restaurant Event_Restaurant Event` ASC) VISIBLE,
  INDEX `fk_Events_Club Event1_idx` (`Club Event_Club Event id` ASC) VISIBLE,
  CONSTRAINT `fk_Events_Restaurant Event1`
    FOREIGN KEY (`Restaurant Event_Restaurant Event`)
    REFERENCES `mydb`.`Restaurant Event` (`Restaurant Event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_Club Event1`
    FOREIGN KEY (`Club Event_Club Event id`)
    REFERENCES `mydb`.`Club Event` (`Club Event id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Destinations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Destinations` (
  `Destinations id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Next Destination id` INT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `DistanceFromDeparturePoint` INT NOT NULL,
  `LocalLanguage` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `Tours_Tour id` INT NULL,
  `Events_Event Id` INT NULL,
  PRIMARY KEY (`Destinations id`),
  INDEX `fk_Destinations_Destinations1_idx` (`Next Destination id` ASC) VISIBLE,
  INDEX `fk_Destinations_Tours1_idx` (`Tours_Tour id` ASC) VISIBLE,
  INDEX `fk_Destinations_Events1_idx` (`Events_Event Id` ASC) VISIBLE,
  CONSTRAINT `fk_Destinations_Destinations1`
    FOREIGN KEY (`Next Destination id`)
    REFERENCES `mydb`.`Destinations` (`Destinations id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Destinations_Tours1`
    FOREIGN KEY (`Tours_Tour id`)
    REFERENCES `mydb`.`Tours` (`Tour id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Destinations_Events1`
    FOREIGN KEY (`Events_Event Id`)
    REFERENCES `mydb`.`Events` (`Event Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Museum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Museum` (
  `Museum id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Museum id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Archeological Space`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Archeological Space` (
  `Archeological Space id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Archeological Space id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historic Center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historic Center` (
  `Historic Center id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Historic Center id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Attraction Characteristics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Attraction Characteristics` (
  `Attraction Characteristics id` INT NOT NULL,
  `Museum_Museum id` INT NOT NULL,
  `Archeological Space_Archeological Space id` INT NOT NULL,
  `Historic Center_Historic Center id` INT NOT NULL,
  PRIMARY KEY (`Attraction Characteristics id`),
  INDEX `fk_Attraction Characteristics_Museum1_idx` (`Museum_Museum id` ASC) VISIBLE,
  INDEX `fk_Attraction Characteristics_Archeological Space1_idx` (`Archeological Space_Archeological Space id` ASC) VISIBLE,
  INDEX `fk_Attraction Characteristics_Historic Center1_idx` (`Historic Center_Historic Center id` ASC) VISIBLE,
  CONSTRAINT `fk_Attraction Characteristics_Museum1`
    FOREIGN KEY (`Museum_Museum id`)
    REFERENCES `mydb`.`Museum` (`Museum id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Attraction Characteristics_Archeological Space1`
    FOREIGN KEY (`Archeological Space_Archeological Space id`)
    REFERENCES `mydb`.`Archeological Space` (`Archeological Space id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Attraction Characteristics_Historic Center1`
    FOREIGN KEY (`Historic Center_Historic Center id`)
    REFERENCES `mydb`.`Historic Center` (`Historic Center id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Attractions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Attractions` (
  `Attraction id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Destinations id` INT NOT NULL,
  `Attraction Characteristics id` INT NOT NULL,
  PRIMARY KEY (`Attraction id`),
  INDEX `fk_Attractions_Destinations1_idx` (`Destinations id` ASC) VISIBLE,
  INDEX `fk_Attractions_Attraction Characteristics1_idx` (`Attraction Characteristics id` ASC) VISIBLE,
  CONSTRAINT `fk_Attractions_Destinations1`
    FOREIGN KEY (`Destinations id`)
    REFERENCES `mydb`.`Destinations` (`Destinations id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Attractions_Attraction Characteristics1`
    FOREIGN KEY (`Attraction Characteristics id`)
    REFERENCES `mydb`.`Attraction Characteristics` (`Attraction Characteristics id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tours` (
  `Tour id` INT NOT NULL,
  `Attractions id` INT NOT NULL,
  `Tour Guide_Tour Guide id` INT NOT NULL,
  `Tour Guide_Language id` INT NOT NULL,
  PRIMARY KEY (`Tour id`),
  INDEX `fk_Tours_Attractions1_idx` (`Attractions id` ASC) VISIBLE,
  INDEX `fk_Tours_Tour Guide1_idx` (`Tour Guide_Tour Guide id` ASC, `Tour Guide_Language id` ASC) VISIBLE,
  CONSTRAINT `fk_Tours_Attractions1`
    FOREIGN KEY (`Attractions id`)
    REFERENCES `mydb`.`Attractions` (`Attraction id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tours_Tour Guide1`
    FOREIGN KEY (`Tour Guide_Tour Guide id` , `Tour Guide_Language id`)
    REFERENCES `mydb`.`Tour Guide` (`Tour Guide id` , `Languages id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Activities` (
  `Activities id` INT NOT NULL,
  `Event Id` INT NULL,
  `Tours id` INT NOT NULL,
  PRIMARY KEY (`Activities id`),
  INDEX `fk_Activities_Events1_idx` (`Event Id` ASC) VISIBLE,
  INDEX `fk_Activities_Tours1_idx` (`Tours id` ASC) VISIBLE,
  CONSTRAINT `fk_Activities_Events1`
    FOREIGN KEY (`Event Id`)
    REFERENCES `mydb`.`Events` (`Event Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Activities_Tours1`
    FOREIGN KEY (`Tours id`)
    REFERENCES `mydb`.`Tours` (`Tour id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Solo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Solo` (
  `idSolo` INT NOT NULL,
  PRIMARY KEY (`idSolo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Family` (
  `Family id` INT NOT NULL,
  PRIMARY KEY (`Family id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Group` (
  `Group id` INT NOT NULL,
  PRIMARY KEY (`Group id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation Category` (
  `Deal Category id` INT NOT NULL,
  `Solo_idSolo` INT NULL,
  `Family_Family id` INT NULL,
  `Group_Group id` INT NULL,
  PRIMARY KEY (`Deal Category id`),
  INDEX `fk_Deal Category_Solo1_idx` (`Solo_idSolo` ASC) VISIBLE,
  INDEX `fk_Deal Category_Family1_idx` (`Family_Family id` ASC) VISIBLE,
  INDEX `fk_Deal Category_Group1_idx` (`Group_Group id` ASC) VISIBLE,
  CONSTRAINT `fk_Deal Category_Solo1`
    FOREIGN KEY (`Solo_idSolo`)
    REFERENCES `mydb`.`Solo` (`idSolo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Deal Category_Family1`
    FOREIGN KEY (`Family_Family id`)
    REFERENCES `mydb`.`Family` (`Family id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Deal Category_Group1`
    FOREIGN KEY (`Group_Group id`)
    REFERENCES `mydb`.`Group` (`Group id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation Cost Deal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservation Cost Deal` (
  `Reservation Cost Deal id` INT NOT NULL,
  `Destinations_Destinations id` INT NOT NULL,
  `Reservation Category_Deal Category id` INT NOT NULL,
  `Cost` FLOAT NOT NULL,
  PRIMARY KEY (`Reservation Cost Deal id`),
  INDEX `fk_Reservation Cost Deal_Destinations1_idx` (`Destinations_Destinations id` ASC) VISIBLE,
  INDEX `fk_Reservation Cost Deal_Reservation Category1_idx` (`Reservation Category_Deal Category id` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation Cost Deal_Destinations1`
    FOREIGN KEY (`Destinations_Destinations id`)
    REFERENCES `mydb`.`Destinations` (`Destinations id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation Cost Deal_Reservation Category1`
    FOREIGN KEY (`Reservation Category_Deal Category id`)
    REFERENCES `mydb`.`Reservation Category` (`Deal Category id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Deal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Deal` (
  `Deal id` INT NOT NULL,
  `Bundles id` INT NOT NULL,
  `Deal_Start_date` DATETIME NOT NULL,
  `Deal_End_date` DATETIME NOT NULL,
  `Deal Cost_id` INT NOT NULL,
  `Deal Category id` INT NOT NULL,
  `Description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`Deal id`),
  INDEX `fk_Deal_Reservation Cost Deal1_idx` (`Deal Cost_id` ASC) VISIBLE,
  INDEX `fk_Deal_Reservation Category1_idx` (`Deal Category id` ASC) VISIBLE,
  INDEX `fk_Deal_Bundles1_idx` (`Bundles id` ASC) VISIBLE,
  CONSTRAINT `fk_Deal_Reservation Cost Deal1`
    FOREIGN KEY (`Deal Cost_id`)
    REFERENCES `mydb`.`Reservation Cost Deal` (`Reservation Cost Deal id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Deal_Reservation Category1`
    FOREIGN KEY (`Deal Category id`)
    REFERENCES `mydb`.`Reservation Category` (`Deal Category id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Deal_Bundles1`
    FOREIGN KEY (`Bundles id`)
    REFERENCES `mydb`.`Bundles` (`Bundles id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bundles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bundles` (
  `Bundles id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Activities_Activities id` INT NOT NULL,
  `Deal id` INT NOT NULL,
  PRIMARY KEY (`Bundles id`, `Activities_Activities id`),
  INDEX `fk_Deal Bundles_Activities1_idx` (`Activities_Activities id` ASC) VISIBLE,
  INDEX `fk_Bundles_Deal1_idx` (`Deal id` ASC) VISIBLE,
  CONSTRAINT `fk_Deal Bundles_Activities1`
    FOREIGN KEY (`Activities_Activities id`)
    REFERENCES `mydb`.`Activities` (`Activities id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bundles_Deal1`
    FOREIGN KEY (`Deal id`)
    REFERENCES `mydb`.`Deal` (`Deal id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trips` (
  `Trip id` INT NOT NULL,
  `Departure Date` VARCHAR(45) NOT NULL,
  `Returning Date` VARCHAR(45) NOT NULL,
  `Sits Available` VARCHAR(45) NOT NULL,
  `CostPerPerson` VARCHAR(45) NOT NULL,
  `Bundles_Bundles id` INT NOT NULL,
  `Traveling Company id` INT NOT NULL,
  PRIMARY KEY (`Trip id`),
  INDEX `fk_Trips_Bundles1_idx` (`Bundles_Bundles id` ASC) VISIBLE,
  INDEX `fk_Trips_Traveling Company1_idx` (`Traveling Company id` ASC) VISIBLE,
  CONSTRAINT `fk_Trips_Bundles1`
    FOREIGN KEY (`Bundles_Bundles id`)
    REFERENCES `mydb`.`Bundles` (`Bundles id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trips_Traveling Company1`
    FOREIGN KEY (`Traveling Company id`)
    REFERENCES `mydb`.`Traveling Company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trips_has_Destinations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trips_has_Destinations` (
  `Trips_Trip id` INT NOT NULL,
  `Destinations_Destinations id` INT NOT NULL,
  PRIMARY KEY (`Trips_Trip id`, `Destinations_Destinations id`),
  INDEX `fk_Trips_has_Destinations_Destinations1_idx` (`Destinations_Destinations id` ASC) VISIBLE,
  INDEX `fk_Trips_has_Destinations_Trips1_idx` (`Trips_Trip id` ASC) VISIBLE,
  CONSTRAINT `fk_Trips_has_Destinations_Trips1`
    FOREIGN KEY (`Trips_Trip id`)
    REFERENCES `mydb`.`Trips` (`Trip id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trips_has_Destinations_Destinations1`
    FOREIGN KEY (`Destinations_Destinations id`)
    REFERENCES `mydb`.`Destinations` (`Destinations id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `Customer ID` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `subname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `age` INT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `call_number` INT NOT NULL,
  PRIMARY KEY (`Customer ID`));


-- -----------------------------------------------------
-- Table `mydb`.`user_has_Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_has_Group` (
  `Group_Group id` INT NOT NULL,
  `user_Customer ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Group_Group id`),
  INDEX `fk_user_has_Group_Group1_idx` (`Group_Group id` ASC) VISIBLE,
  INDEX `fk_user_has_Group_user1_idx` (`user_Customer ID` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_Group_Group1`
    FOREIGN KEY (`Group_Group id`)
    REFERENCES `mydb`.`Group` (`Group id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_Group_user1`
    FOREIGN KEY (`user_Customer ID`)
    REFERENCES `mydb`.`user` (`Customer ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Family_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Family_has_user` (
  `Family_Family id` INT NOT NULL,
  `user_Customer ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Family_Family id`),
  INDEX `fk_Family_has_user_Family1_idx` (`Family_Family id` ASC) VISIBLE,
  INDEX `fk_Family_has_user_user1_idx` (`user_Customer ID` ASC) VISIBLE,
  CONSTRAINT `fk_Family_has_user_Family1`
    FOREIGN KEY (`Family_Family id`)
    REFERENCES `mydb`.`Family` (`Family id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Family_has_user_user1`
    FOREIGN KEY (`user_Customer ID`)
    REFERENCES `mydb`.`user` (`Customer ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Solo_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Solo_has_user` (
  `Solo_idSolo` INT NOT NULL,
  `user_Customer ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Solo_idSolo`),
  INDEX `fk_Solo_has_user_Solo1_idx` (`Solo_idSolo` ASC) VISIBLE,
  INDEX `fk_Solo_has_user_user2_idx` (`user_Customer ID` ASC) VISIBLE,
  CONSTRAINT `fk_Solo_has_user_Solo1`
    FOREIGN KEY (`Solo_idSolo`)
    REFERENCES `mydb`.`Solo` (`idSolo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solo_has_user_user2`
    FOREIGN KEY (`user_Customer ID`)
    REFERENCES `mydb`.`user` (`Customer ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reservations` (
  `Reservation id` INT NOT NULL,
  `Bundles id` INT NOT NULL,
  `Customer ID` VARCHAR(45) NOT NULL,
  `Reservation Date` DATETIME NOT NULL,
  `Given Amount` FLOAT NOT NULL,
  `SubStore_id` INT NOT NULL,
  INDEX `fk_Reservations_user1_idx` (`Customer ID` ASC) VISIBLE,
  INDEX `fk_Reservations_Sub Store1_idx` (`SubStore_id` ASC) VISIBLE,
  PRIMARY KEY (`Reservation id`),
  INDEX `fk_Reservations_Bundles1_idx` (`Bundles id` ASC) VISIBLE,
  CONSTRAINT `fk_Reservations_user1`
    FOREIGN KEY (`Customer ID`)
    REFERENCES `mydb`.`user` (`Customer ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservations_Sub Store1`
    FOREIGN KEY (`SubStore_id`)
    REFERENCES `mydb`.`Sub Store` (`SubStore_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservations_Bundles1`
    FOREIGN KEY (`Bundles id`)
    REFERENCES `mydb`.`Bundles` (`Bundles id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
